---
- hosts: localhost
  gather_facts: yes
  roles:
    - ansible_network.cli_rm_builder.run
  vars:
    docstring: ./rm_models/isam_bridge.yaml
    rm_dest: ./tmp/
    resource: bridges
    collection_org: isam
    collection_name: isam
    ansible_connection: local
