---
- hosts: localhost
  gather_facts: yes
  roles:
    - ansible_network.cli_rm_builder.run
  vars:
    #docstring: /home/jank/resource_module_models_isam/models/isam/vlans/isam_vlans.yaml
    rm_dest: .
    resource: vlans
    collection_org: isam
    collection_name: isam
    ansible_connection: local
