---
- hosts: DS-LIN-TEST-01
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Gather Interfaces Facts
      nokia.isam.isam_interfaces:
        state: gathered
      timeout: 300
      register: result
