# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the isam_interfaces module
"""


class InterfacesArgs(object):  # pylint: disable=R0903
    """The arg spec for the isam_interfaces module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "name": {"type": "str", "aliases": ["id"]},
                "admin_up": {"type": "bool", "aliases": ["admin-up"]},
                "link_updown_trap": {"type": "bool", "aliases": ["link-updown-trap"]},
                "user": {"type": "str"},
                "severity": {
                    "type": "str",
                    "choices": [
                        "indeterminate",
                        "warning",
                        "minor",
                        "major",
                        "critical",
                        "no-alarms",
                        "default",
                        "no-value",
                    ],
                },
                "port_type": {
                    "type": "str",
                    "aliases": ["port-type"],
                    "choices": ["uni", "nni", "hc-uni", "uplink"],
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
