# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the isam_vlans module
"""


class VlansArgs(object):  # pylint: disable=R0903
    """The arg spec for the isam_vlans module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "id": {"type": "str"},
                "name": {"type": "str"},
                "mode": {
                    "type": "str",
                    "choices": [
                        "cross-connect",
                        "residential-bridge",
                        "qos-aware",
                        "layer2-terminated",
                        "mirror",
                    ],
                },
                "sntp-proxy": {"type": "bool"},
                "priority": {"type": "int"},
                "vmac-not-in-opt61": {"type": "bool"},
                "new-broadcast": {
                    "type": "str",
                    "choices": ["inherit", "enable", "disable"],
                    "default": "inherit",
                },
                "protocol-filter": {
                    "type": "str",
                    "choices": [
                        "pass-all",
                        "pass-pppoe",
                        "pass-ipoe",
                        "pass-pppoe-ipoe",
                        "pass-ipv6oe",
                        "pass-pppoe-ipv6oe",
                        "pass-ipoe-ipv6oe",
                        "pass-pppoe-ipoe-ipv6oe",
                    ],
                    "default": "pass-all",
                },
                "pppoe-relay-tag": {
                    "type": "str",
                    "choices": ["true", "false", "configurable"],
                },
                "drly-srv-usr-side": {"type": "bool", "default": False},
                "dhcp-opt82-ext": {
                    "type": "str",
                    "choices": ["enable", "add-or-forward"],
                },
                "dhcp-opt82-nni": {"type": "bool"},
                "dhcp-opt82-uplink": {"type": "bool"},
                "circuit-id-dhcp": {
                    "type": "str",
                    "choices": ["physical-id"],
                },
                "remote-id-dhcp": {
                    "type": "str",
                    "choices": ["customer-id"],
                },
                "relay-id-dhcp": {"type": "bool"},
                "dhcp-linerate": {"type": "bool"},
                "pppoe-linerate": {"type": "bool"},
                "dhcpv6-linerate": {"type": "bool"},
                "pppoe-l2-encaps": {"type": "bool"},
                "dhcp-l2-encaps": {"type": "bool"},
                "dhcpv6-l2-encaps": {"type": "bool"},
                "l2-encaps1": {"type": "bool"},
                "pppoer-vlanaware": {"type": "bool"},
                "dhcpr-vlanaware": {"type": "bool"},
                "dhcpv6r-vlanaware": {"type": "bool"},
                "circuit-id-pppoe": {
                    "type": "str",
                    "choices": ["physical-id"],
                },
                "remote-id-pppoe": {
                    "type": "str",
                    "choices": ["customer-id"],
                },
                "dhcpv6-itf-id": {
                    "type": "str",
                    "choices": ["physical-id"],
                },
                "dhcpv6-remote-id": {
                    "type": "str",
                    "choices": ["customer-id"],
                },
                "dhcpv6-relay-id": {"type": "bool"},
                "dhcpv6-trst-port": {"type": "bool"},
                "enterprise-number": {"type": "int"},
                "vmac-translation": {"type": "bool"},
                "vmac-dnstr-filter": {"type": "bool"},
                "icmpv6-sec-fltr": {"type": "bool"},
                "new-secure-fwd": {
                    "type": "str",
                    "choices": ["inherit", "enable", "disable"],
                },
                "aging-time": {"type": "int"},
                "l2cp-transparent": {"type": "bool"},
                "in-qos-prof-name": {"type": "str"},
                "ipv4-mcast-ctrl": {"type": "bool"},
                "ipv6-mcast-ctrl": {"type": "bool"},
                "mac-mcast-ctrl": {"type": "bool"},
                "dis-proto-rip": {"type": "bool"},
                "proto-ntp": {"type": "bool"},
                "dis-ip-antispoof": {"type": "bool"},
                "unknown-unicast": {"type": "bool"},
                "pt2ptgem-flooding": {"type": "bool"},
                "mac-movement-ctrl": {"type": "bool"},
                "cvlan4095passthru": {
                    "type": "str",
                    "choices": ["passthru", "not-applicable"],
                },
                "arp-snooping": {"type": "bool"},
                "arp-polling": {"type": "bool"},
                "arp-polling-ip": {"type": "str"},
                "mac-unauth": {"type": "bool"},
            },
        },
        "state": {
            "type": "str",
            "choices": ["merged", "replaced", "overridden", "deleted", "gathered"],
        },
    }  # pylint: disable=C0301
